# Generated by Django 4.2.16 on 2024-12-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
