# Generated by Django 5.1.2 on 2024-12-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0006_alter_user_avatar_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='users_comme_user_id_cd5895_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['room'], name='users_comme_room_id_b10a63_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['timestamp'], name='users_comme_timesta_ab9ef0_idx'),
        ),
    ]
