# Generated by Django 4.2.17 on 2024-12-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar_alter_user_name_mychats'),
        ('users', '0007_friendship'),
    ]

    operations = [
    ]
