# Generated by Django 4.2.17 on 2024-12-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_comment_delete_activitylog_and_more'),
        ('users', '0008_merge_20241211_0425'),
    ]

    operations = [
    ]
