# Generated by Django 5.1.4 on 2024-12-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
        ('users', '0009_merge_20241211_0446'),
    ]

    operations = [
    ]
