    # Generated by Django 4.2.16 on 2024-12-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
