# Generated by Django 5.1.4 on 2024-12-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
